version: '2.1'

services:
  mongodb:
    image: "mongo"
    ports:
     - "27017:27017"
  vuttr:
    image: vuttr
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
